### ISSUE TITLE
Error in Facebook app reviewing process

### ISSUE THREAD

**Issue by barry800414** [Yoctol/bottender#137]
I am using bottender to build a facebook messenger bot. 
However, every time I send review request for `pages_messages` permission in facebook developer console, my server will get some error, so that I cannot pass the review. The full error messages are as following:

```
(node:14801) UnhandledPromiseRejectionWarning: Error: Messenger API - 100 GraphMethodException Unsupported get request. Object with ID '1838982186136447' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
    at handleError (/home/goodjob/wei-ming-check-in-bot/node_modules/messaging-api-messenger/lib/MessengerClient.js:94:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:14801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:14801) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined
    at MessengerConnector.getUniqueSessionKey (/home/ming/wei-ming-check-in-bot/node_modules/bottender/lib/bot/MessengerConnector.js:103:18)
    at /home/ming/wei-ming-check-in-bot/node_modules/bottender/lib/bot/Bot.js:96:42
    at /home/ming/wei-ming-check-in-bot/node_modules/bottender/lib/express/createMiddleware.js:12:28
    at Layer.handle [as handle_request] (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/route.js:137:13)
    at /home/ming/wei-ming-check-in-bot/node_modules/bottender/lib/express/verifyMessengerSignature.js:8:12
    at Layer.handle [as handle_request] (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/layer.j
    at /home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ming/wei-ming-check-in-bot/node_modules/express/lib/router/index.js:275:10)
    at /home/ming/wei-ming-check-in-bot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/ming/wei-ming-check-in-bot/node_modules/raw-body/index.js:224:16)
    at done (/home/ming/wei-ming-check-in-bot/node_modules/raw-body/index.js:213:7)
(node:14801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```

### How to repeat the bug
1. Write a messenger bot without `try catch` statement and `onError` handler
2. In facebook developer console, ask for `messages`  permission in `Messenger` tab
![2017-12-30 4 56 47](https://user-images.githubusercontent.com/3805975/34472637-4bf1c7da-efa1-11e7-9627-c1a00faa88a6.png)

3. Goto `Webhook` tab in facebook, press `test` for `messages`
![2018-01-02 9 44 06](https://user-images.githubusercontent.com/3805975/34472660-9c6324f2-efa1-11e7-88ce-b3825bd6811d.png)

then server will get same error message

If I need to provide more information, please kindly tell me.

**Comment by tw0517tw** [comment]
There are 2 unhandled promise error in your snippet. 
1. `Error: Messenger API - 100 GraphMethodException Unsupported get request`

This one is likely from unable to query Messenger user profile from the sender. You can use `process.on('unhandledRejection')` or `try-catch` or `promise.catch()` to print the error for more information.

2. `TypeError: Cannot read property 'message' of undefined`

This one is from the `webhook test`. That's because the request from webhook test is not in the same form as what we actually get from real Messenger Platform requests, thus `bottender` can't parse them. I guess you can skip the test button thing for now.

-----

Also, you can set `DEBUG` environment variable to `bottender/bot/Bot` to print all the http requests the bot receives, this may also help you debug.

**Comment by chentsulin** [comment]
@LittleWhiteYA please help follow up this issue.

**Comment by barry800414** [comment]
Sorry, currently I do not have enough time to track this problem. 
Close it. 
If I can fully understand where the problem in the future, I will reopen it or create new issue.
