### ISSUE TITLE
[Fb Messenger] - Error about user

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#221]
With this new policy about facebook now i'm getting this error:

```
TypeError: Cannot assign to read only property 'user' of object '#<Object>'
    at MessengerConnector.updateSession (C:\Users\Avell\projetos\asksuite-facebook\node_modules\bottender\lib\bot\MessengerConnector.js:160:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by tw0517tw** [comment]
I can reproduce this with some condition:
1. use memory session store (the default)
2. subscribe to standby events on Messenger
3. when user click postback buttons

Are you in the same condition?

It seems that Messenger Platform is sending both `messaging` and `standby` events to the current thread owner when click on buttons, even when the button is send by this current App. I'm not sure if it was like this before, but it seems to cause some race condition on the memory session store. We'll look into this.
