### ISSUE TITLE
If Telegram handler throw an error, bot enter failed state because of session

### ISSUE THREAD

**Issue by trueshura** [Yoctol/bottender#231]
`failed state` === `stops processing messages` (at least for this user)
here is error log

```
TypeError: Cannot assign to read only property 'user' of object '#<Object>'
    at myTelegramConnector.updateSession (/app/node_modules/bottender/lib/bot/TelegramConnector.js:99:20)
    at /app/node_modules/bottender/lib/bot/Bot.js:129:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

here is failed code
```
    if (body.message) {
      session.user = body.message.from;
    } else if (body.edited_message) {
      session.user = body.edited_message.from;
    } else if (body.inline_query) {
      session.user = body.inline_query.from;
    } else if (body.chosen_inline_result) {
      session.user = body.chosen_inline_result.from;
    } else if (body.callback_query) {
      session.user = body.callback_query.from;
    } else if (body.shipping_query) {
      session.user = body.shipping_query.from;
    } else if (body.pre_checkout_query) {
      session.user = body.pre_checkout_query.from;
    }

    if (session.user) {
      session.user._updatedAt = new Date().toISOString();
      Object.freeze(session.user);
    }
    Object.defineProperty(session, 'user', {
      configurable: false,
      enumerable: true,
      writable: false,
      value: session.user,
    });
```

PS session is default one (i suppose it's `CacheBasedSessionStore`)

**Comment by chentsulin** [comment]
duplicate with #221
