### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by roonie007** [Yoctol/bottender#246]
Hey guys,

I am using the TelegramBot with long polling, if I left the Bot without any interaction for few minutes I get this error : 
```bash
TypeError: Cannot read property 'data' of undefined
    at handleError (~\****\node_modules\messaging-api-telegram\lib\TelegramClient.js:17:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
``` 
In the TelegramClient.js:17 we find this : 
```javascript
function handleError(err) {var _err$response$data =
  /* this line is the line 17 --> */ err.response.data;const error_code = _err$response$data.error_code,description = _err$response$data.description;
  const msg = `Telegram API - ${error_code} ${description || ''}`; // eslint-disable-line camelcase
  throw new _axiosError2.default(msg, err);
}
```

So I did log the err parameter and it gives me this : 
```javascript
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:628:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.17.1',
        'Content-Length': 91 },
     baseURL: 'https://api.telegram.org/TELEGRAM_BOT_TOKEN/',
     method: 'post',
     url: 'https://api.telegram.org/TELEGRAM_BOT_TOKEN/getUpdates',
     data: '{"limit":10,"timeout":60,"allowed_updates":["message","callback_query"],"offset":482395741}' },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { maxRedirects: 21,
        protocol: 'https:',
        hostname: 'api.telegram.org',
        port: null,
        path: '/TELEGRAM_BOT_TOKEN/getUpdates',
        method: 'post',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        pathname: '/TELEGRAM_BOT_TOKEN/getUpdates' },
     _redirectCount: 0,
     _bufferedWrites: [ [Object] ],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 91,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /TELEGRAM_BOT_TOKEN/getUpdates HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nUser-Agent: axios/0.17.1\r\nContent-Length: 91\r\nHost: api.telegram.org\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/TELEGRAM_BOT_TOKEN/getUpdates',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://api.telegram.org/TELEGRAM_BOT_TOKEN/getUpdates' },
  response: undefined }
```

even I am getting that error , if I send a message to the Telegram Bot, it still answers me correctly and everything is working fine.

So can you guys handel this error ?
That would be awsome

Thanks

**Comment by chentsulin** [comment]
Try set `timeout` to `0` (or remove it) if you want to run long polling without any timeout.

```js
bot.createLongPollingRuntime({
  limit: 10, // Limits the number of updates to be retrieved. Defaults to 100.
  timeout: 0, // Timeout in seconds for long polling. Defaults to 0.
  allowed_updates: ['message', 'callback_query'], // List the types of updates you want your bot to receive
});
```
