### ISSUE TITLE
Line leave or unfollow 

### ISSUE THREAD

**Issue by wtflink** [Yoctol/bottender#258]
I am using LineBot with sendMethod: 'reply'.
While receiving line leave or unfollow event, this error occur
```
Error: LINE API - The request body has 1 error(s)
 - replyToken: May not be empty
     at handleError (/app/node_modules/messaging-api-line/lib/LineClient.js:41:9)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by wtflink** [comment]
Hi, @yusef-ho
You still need to handle this event with `onUnfollow` or `onLeave` but don't do anything require replyToken such as `sendText`, `sendImage`..., cause there's no replyToken in the event.

If you want to handle this event with literally doing nothing, try this:
```
const handler = new MessengerHandler()
  .onUnfollow(() => {})
  .onEvent(async context => {
    await context.sendText("Hello world");
  })
```
or you can try [bottender-compose](https://github.com/Yoctol/bottender-compose)
```
const { doNothing } = require('bottender-compose');

const handler = new MessengerHandler()
  .onLeave(doNothing())
  .onEvent(async context => {
    await context.sendText("Hello world");
  })```
