### ISSUE TITLE
LINEBOT - Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by wiasliaw77210** [Yoctol/bottender#315]
Here is my code
```
const JoinHandle = new LineHandler()
	.onEvent(async context=>{
		if(context.event.isFollow){
			async context => {
				await context.replyTemplate('this is a template', {
					type: 'buttons',
					title: 'Menu',
					text: 'Please select',
					actions: [
						{
							type: 'uri',
							label: 'Add to cart',
	      					        data:'https://www.google.com/',
						},
						{
							type: 'uri',
							label: 'Add to cart',
	      					       data:'https://www.google.com/',
						},
					],
				});
				console.log(context.event);
			}
		}else if(context.event.isUnfollow){
			await console.log(context.event);
		}else{
			await console.log(context.event);
		}
	}).onUnhandled(async (context,err)=>{
		console.log(err.message);
	}).onError(async (context,err)=>{
		console.log(err.message);
	});
```
The error message is just like title, I dont know why.

**Comment by chentsulin** [comment]
Hi @wiasliaw77210, there are no second argument `err` in `onUnhandled` callback:

```js
.onUnhandled(async context=>{
  console.log(context.event);
})
```

**Comment by wiasliaw77210** [comment]
```
const JoinHandle = new LineHandler()
	.onEvent(async context=>{
		if(context.event.isFollow){
			async context => {
				await context.replyTemplate('this is a template', {
					type: 'buttons',
					title: 'Menu',
					text: 'Please select',
					actions: [
						{
							type: 'uri',
							label: 'Add to cart',
	      					data:'https://www.google.com/',
						},
						{
							type: 'uri',
							label: 'Add to cart',
	      					data:'https://www.google.com/',
						},
					],
				});
				console.log(context.event);
			}
		}else if(context.event.isUnfollow){
			await console.log(context.event);
		}else{
			await console.log(context.event);
		}
	}).onUnhandled(async (context)=>{
		console.log(context.event);
	}).onError(async (context,err)=>{
		console.log(err.message);
	});

```
There is no error message, but i cant get my mesage from my bot.
(Using Ngrok for test)

**Comment by chentsulin** [comment]
You should remove an unnecessary async function in `context.event.isFollow` if condition:

```js
const JoinHandle = new LineHandler()
  .onEvent(async context => {
    if (context.event.isFollow) {
      // You have an unnecessary async function in previous version
      await context.replyTemplate('this is a template', {
        type: 'buttons',
        title: 'Menu',
        text: 'Please select',
        actions: [
          {
            type: 'uri',
            label: 'Add to cart',
            data: 'https://www.google.com/',
          },
          {
            type: 'uri',
            label: 'Add to cart',
            data: 'https://www.google.com/',
          },
        ],
      });
      console.log(context.event);
    } else if (context.event.isUnfollow) {
      console.log(context.event);
    } else {
      console.log(context.event);
    }
  }).onUnhandled(async (context) => {
    console.log(context.event);
  }).onError(async (context, err) => {
    console.log(err.message);
  });
```

**Comment by wiasliaw77210** [comment]
```js
const JoinHandle = new LineHandler()
	.onEvent(async (context,err)=>{
		if(context.event.isFollow){
			await context.replyTemplate('this is a template', {
				type: 'buttons',
				title: 'Menu',
				text: 'Please select',
				actions: [
					{
						type: 'uri',
						label: 'Add to cart',
	      				data:'https://www.google.com/',
					},
					{
						type: 'uri',
						label: 'Add to cart',
      					data:'https://www.google.com/',
					},
				],
			});
				console.log(context.event);
		}else if(context.event.isUnfollow){
			console.log("Unfollow");
			console.log(context.event);
		}else{
			console.log("Something else");
			console.log(err.message);
		}
	}).onUnhandled(async (context)=>{
		console.log(context.event);
	}).onError(async (context,err)=>{
		console.log(err.message);
	});
```
However, it will turn out to be "context.replyTemplate is not a function"

**Comment by chentsulin** [comment]
Please check out line-builder example - https://github.com/Yoctol/bottender/tree/master/examples/line-builder

And see whether it works on your machine or not.

**Comment by wiasliaw77210** [comment]
It works on my machine.
error message
```
TypeError: context.replyTemplate is not a function
    at LineHandler.onFollow (/media/leewei/DATA/line_api_server/platform/LinePlat/handler/joinhandler.js:14:17)
    at /media/leewei/DATA/line_api_server/node_modules/bottender/lib/handlers/Handler.js:123:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by chentsulin** [comment]
@wiasliaw77210 The error stack show that this error is thrown from `.onFollow (joinhandler.js:14:17)` but you previous code snippet even didn't have an `onFollow` call.

I think you should check if you pasted the wrong code here.

**Comment by chentsulin** [comment]
Hi @wiasliaw77210 
I think you may have solved your problem. If you have further questions, you can open a new question [with bottender tag on stackoverflow](https://stackoverflow.com/questions/tagged/bottender)
