### ISSUE TITLE
`bottender -h` command fails after 0.15.10

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/bottender#357]
It will show help command in previous versions.

```
$ bottender -h
▒▒ An unexpected error occurred!
  Error: Option requires argument: -h (alias for --help)
    at arg (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\node_modules\arg\index.js:70:12)
    at getArgs (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\lib\cli\providers\sh\utils\getArgs.js:18:69
)
    at main (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\lib\cli\index.js:27:37)
    at Object.<anonymous> (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\lib\cli\index.js:105:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17) Error: Option requires argument: -h (alias for --help)
    at arg (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\node_modules\arg\index.js:70:12)
    at getArgs (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\lib\cli\providers\sh\utils\getArgs.js:18:69
)
    at main (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\lib\cli\index.js:27:37)
    at Object.<anonymous> (C:\Users\tw0517tw\AppData\Roaming\npm\node_modules\bottender\lib\cli\index.js:105:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
undefined
```

**Comment by kidkcl** [comment]
This works on my local environment...
```
$ bottender -v
0.15.10
$ bottender -h

    bottender <command>

    Commands:

      Platform

        messenger   <command>   Manage your Messenger command
        telegram    <command>   Manage your Telegram command
        line        <command>   Manage your LINE command
        viber       <command>   Manage your Viber command

      Global

        init                    Init a bot skeleton
        help                    Show this help

    Configs:

        --skip-validate         Skip the config validation

    Examples:

    - Init a bot

      $ bottender init

    - Get the help

      $ bottender help
      $ bottender messenger help

    - Manage the Messenger command

      $ bottender messenger webhook set

    - Skip config validation

      $ bottender messenger profile set --skip-validate
```
