### ISSUE TITLE
[Bug] - Invalid Parameter 

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#372]
Hi, i'm using the lastest version of bottender, but i cant understand this error and when its occur.

```
2018-11-14T13:45:19.651466944Z app[web.1]: Error: Messenger API - 100 OAuthException Invalid parameter
2018-11-14T13:45:19.651474365Z app[web.1]:     at handleError (/app/node_modules/bottender-asksuite/node_modules/messaging-api-messenger/lib/MessengerClient.js:90:11)
2018-11-14T13:45:19.651484900Z app[web.1]:     at <anonymous>
2018-11-14T13:45:19.651489724Z app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
2018-11-14T13:45:19.651493764Z app[web.1]:     at process.wrappedFunction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:276:51)
2018-11-14T13:45:19.651497834Z app[web.1]:
2018-11-14T13:45:19.651501593Z app[web.1]: Error Message -
2018-11-14T13:45:19.651505343Z app[web.1]:   Messenger API - 100 OAuthException Invalid parameter
2018-11-14T13:45:19.651509518Z app[web.1]:
2018-11-14T13:45:19.651513325Z app[web.1]: Request -
2018-11-14T13:45:19.651518041Z app[web.1]:   GET https://graph.facebook.com/v3.0/2342872412421533?access_token=XXXXXX&appsecret_proof=XXXXX
2018-11-14T13:45:19.651524753Z app[web.1]:
2018-11-14T13:45:19.651528473Z app[web.1]:
2018-11-14T13:45:19.651532356Z app[web.1]: Response -
2018-11-14T13:45:19.651536236Z app[web.1]:   400 Bad Request
2018-11-14T13:45:19.651540170Z app[web.1]:
2018-11-14T13:45:19.651543940Z app[web.1]: Response Data -
2018-11-14T13:45:19.651547638Z app[web.1]:   {
2018-11-14T13:45:19.651551366Z app[web.1]:     "error": {
2018-11-14T13:45:19.651555230Z app[web.1]:       "message": "Invalid parameter",
2018-11-14T13:45:19.651559778Z app[web.1]:       "type": "OAuthException",
2018-11-14T13:45:19.651564270Z app[web.1]:       "code": 100,
2018-11-14T13:45:19.651568490Z app[web.1]:       "error_data": {
2018-11-14T13:45:19.651572502Z app[web.1]:         "blame_field_specs": [
2018-11-14T13:45:19.651576746Z app[web.1]:           [
2018-11-14T13:45:19.651580801Z app[web.1]:             "No matching user: No matching user found"
2018-11-14T13:45:19.651585443Z app[web.1]:           ]
2018-11-14T13:45:19.651589530Z app[web.1]:         ]
2018-11-14T13:45:19.651593797Z app[web.1]:       },
2018-11-14T13:45:19.651599098Z app[web.1]:       "error_subcode": 2018001,
2018-11-14T13:45:19.651603702Z app[web.1]:       "is_transient": false,
2018-11-14T13:45:19.651608063Z app[web.1]:       "error_user_title": "No matching user",
2018-11-14T13:45:19.651612787Z app[web.1]:       "error_user_msg": "No matching user found",
2018-11-14T13:45:19.651617515Z app[web.1]:       "fbtrace_id": "Cr+US3ppBJK"
2018-11-14T13:45:19.651632447Z app[web.1]:     }
2018-11-14T13:45:19.651637132Z app[web.1]:   }
````

**Comment by tw0517tw** [comment]
Sometimes there would be invalid user ID in the events and we can't do anything about that. Maybe you can try to report to Facebook Support(https://developers.facebook.com/support/bugs/).

**Comment by chentsulin** [comment]
It's hard to tell anything without more detail information. This error may caused by many different reasons, for example:

- wrong token
- expired token
- wrong id
- facebook internal issue
- ... and so on

You can find a lot of similar issues on Stackoverflow:

- [No matching user found - OAuthException Error in Facebook Messenger](https://stackoverflow.com/questions/49394650/no-matching-user-found-oauthexception-error-in-facebook-messenger)
- [Facebook API: (#100) No matching user found](https://stackoverflow.com/questions/45523746/facebook-api-100-no-matching-user-found)
- [I am getting message: '(#100) No matching user found', when using the facebook messenger bot sample tutorial code](https://stackoverflow.com/questions/38255365/i-am-getting-message-100-no-matching-user-found-when-using-the-facebook-m)
