### ISSUE TITLE
when will .build() execute? handler is not a function

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#394]
Hello, currently i have handlers cross-dependent as following

````javascript
// mainHandler
const registrationHandler = require('./registrationHandler')
module.exports = new LineHandler()
.onFollow(followHandler)
.onEvent(condition([
    [context => {
        if(!couldNotFindUserOnFirebase) return true
        return false
    }, async context => {
        // do something
        await registrationHandler(context)
    }],
    [context => false, sendText('b')],
    [context => true, sendText('c')],
])
.build()
````
````javascript
// registrationHandler
const mainHandler = require('./mainHandler')
module.exports = new LineHandler()
.onEvent(branch(
    context => {
        if(!findUser){
            return true
        }
        return false
    },
    async context => {
        // Handle Registration Logic
    },
    async context => {
        // Do something
        // Back to MainHandler
        await mainHandler(context)
    }
))
````
And the following error showed
````
TypeError: mainHandler is not a function
    at module.exports.LineHandler.onEvent.branch (/Users/yusef/Documents/Projects/linebot/handlers/botServices/registrationHandler.js:39:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
````
Thanks

**Comment by yusef-ho** [comment]
Sorry, it's the problem of circular dependencies. Closed
