### ISSUE TITLE
npm install get fatal error: too many errors emitted, stopping now [-ferror-limit=]

### ISSUE THREAD

**Issue by hilezi** [Yoctol/bottender#586]
**Describe the bug**

after macOS upgraded yesterday

"npm install" get fatal errors

also appear in `npx create-bottender-app my-app`

I am tried to delete `.node-gyp/`, delete node_modules, delete "package-lock.json"...

however, the bot is working yesterday. now getting errors when verifying webhook URL 

```
[bot] App has started
[bot] server is running on 5000 port...
[bot] line webhook url: https://63db447a.ngrok.io/webhooks/line
[bot] TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type undefined
[bot]     at prepareSecretKey (internal/crypto/keys.js:302:13)
[bot]     at new Hmac (internal/crypto/hash.js:101:9)
[bot]     at Object.createHmac (crypto.js:139:10)
[bot]     at LineConnector.verifySignature (/Users/pleasurazy/git/life/packages/bot/node_modules/bottender/dist/line/LineConnector.js:184:14)
[bot]     at LineConnector.preprocess (/Users/pleasurazy/git/life/packages/bot/node_modules/bottender/dist/line/LineConnector.js:199:19)
[bot]     at /Users/pleasurazy/git/life/packages/bot/node_modules/@bottender/express/dist/registerRoutes.js:15:56
[bot]     at Layer.handle [as handle_request] (/Users/pleasurazy/git/life/packages/bot/node_modules/express/lib/router/layer.js:95:5)
[bot]     at trim_prefix (/Users/pleasurazy/git/life/packages/bot/node_modules/express/lib/router/index.js:317:13)
[bot]     at /Users/pleasurazy/git/life/packages/bot/node_modules/express/lib/router/index.js:284:7
[bot]     at Function.process_params (/Users/pleasurazy/git/life/packages/bot/node_modules/express/lib/router/index.js:335:12)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. npm install

**Expected behavior**
1. no error

**Screenshots**
```
$npm i

> fsevents@1.2.11 install /Users/pleasurazy/git/life/packages/bot/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:53:
In file included from /Users/pleasurazy/Library/Caches/node-gyp/10.15.1/include/node/uv.h:56:
In file included from /usr/local/include/stdint.h:59:
......
......
......repeatly
......
......
In file included from /usr/local/include/stdint.h:59:
/usr/local/include/stdint.h:2:10: error: #include nested too deeply
#include <stddef.h>
         ^
/usr/local/include/stdint.h:59:11: error: #include nested too deeply
# include <stdint.h>
          ^
/usr/local/include/stdint.h:72:11: error: #include nested too deeply
# include <sys/types.h>
          ^
/usr/local/include/stdint.h:76:10: error: #include nested too deeply
#include <limits.h>
         ^
/usr/local/include/stdint.h:82:11: error: #include nested too deeply
# include <inttypes.h>
          ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:53:
In file included from /Users/pleasurazy/Library/Caches/node-gyp/10.15.1/include/node/uv.h:62:
In file included from /Users/pleasurazy/Library/Caches/node-gyp/10.15.1/include/node/uv/unix.h:28:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dirent.h:135:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:94:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:66:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:110:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:197:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_user_time;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:198:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_system_time;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:199:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_pkg_idle_wkups;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:200:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_interrupt_wkups;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:201:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_pageins;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:202:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_wired_size;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:203:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_resident_size;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:204:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_phys_footprint;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:205:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_proc_start_abstime;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:206:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_proc_exit_abstime;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:211:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_user_time;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:212:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_system_time;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:213:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_pkg_idle_wkups;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:214:2: error:
      unknown type name 'uint64_t'
        uint64_t ri_interrupt_wkups;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pleasurazy/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/pleasurazy/.nvm/versions/node/v10.15.1/bin/node" "/Users/pleasurazy/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pleasurazy/git/life/packages/bot/node_modules/fsevents
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 881379 packages in 9.248s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Additional context**
- MacOS 10.15.2（19C57）
- Node v12.14.0
- npm 6.13.4

I don't have any idea on this, and other packages working fine, so I report it.

**Comment by chentsulin** [comment]
Hi @hilezi, the following error message happens when your LINE `channelSecret` is `undefined`. Please check your `.env` and `bottender.config.js` files and make sure that it has been set correctly.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type undefined
```

We may improve this error message in the next release.

The `node-gyp` error seems not a Bottender issue and related to your XCode settings or your node version. (the error shows that you are using `/Users/pleasurazy/.nvm/versions/node/v10.15.1`, not `Node v12.14.0`)

**Comment by hilezi** [comment]
Thanks for the reply,

After setting `.env`, it's working!

I am looking forward to bottender next release!

thanks

**Comment by chentsulin** [comment]
The error message has been improved in https://github.com/Yoctol/bottender/releases/tag/v1.1.0
