### ISSUE TITLE
nextDialog is not a function

### ISSUE THREAD

**Issue by dcsan** [Yoctol/bottender#704]
**Describe the bug**

tried adding a simple script with a router
https://bottender.js.org/docs/en/channel-messenger-handling-events

```js
const { router, text } = require('bottender/router');

async function SayHi(context) {
  await context.sendText('Hi!');
}

async function SayHello(context) {
  await context.sendText('Hello!');
}

async function App() {
  return router([
    // return the `SayHi` action when receiving "hi" text messages
    text('hi', SayHi),
    // return the `SayHello` action when receiving "hello" text messages
    text('hello', SayHello),
  ]);
}
```

and I just get this error on any incoming messages

```
TypeError: nextDialog is not a function
    at /Users/dcollier/dev/covid/covidbot/bot/node_modules/bottender/dist/bot/Bot.js:37:32
    at Generator.next (<anonymous>)
    at /Users/dcollier/dev/covid/covidbot/bot/node_modules/bottender/dist/bot/Bot.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dcollier/dev/covid/covidbot/bot/node_modules/bottender/dist/bot/Bot.js:4:12)
    at Run (/Users/dcollier/dev/covid/covidbot/bot/node_modules/bottender/dist/bot/Bot.js:34:16)
    at /Users/dcollier/dev/covid/covidbot/bot/node_modules/bottender/dist/bot/Bot.js:158:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

**Comment by dcsan** [comment]
it's in this transpiled JS method:

```js
function run(action) {
    return function Run(context, props = {}) {
        return __awaiter(this, void 0, void 0, function* () {
            let nextDialog = action;
            debugAction(`Current Action: ${nextDialog.name || 'Anonymous'}`);
            nextDialog = yield nextDialog(context, props);
            while (typeof nextDialog === 'function') {
                debugAction(`Current Action: ${nextDialog.name || 'Anonymous'}`);
                nextDialog = yield nextDialog(context, {});
            }
            return nextDialog;
        });
    };
}
exports.run = run;
```

**Comment by dcsan** [comment]
I also tried some routes with just text responses same problem

```
const { router, route, text } = require('bottender/router');

async function Unknown(context) {
  await context.sendText('Sorry. I do not understand what you say.');
}

async function replyTest(context) {
  await context.sendText('reply to something')
}

async function App(context) {
  return router([
    text('test', replyTest),
    text(/^(hi|hello)$/i, SayHi),
    // return the `Unknown` action when when no other route matches the incoming text message
    text('*', Unknown),
  ]);
}

async function SayHi(context) {
  await context.sendText('Hi!');
}
```

**Comment by chentsulin** [comment]
Hi @dcsan, if you're writing this `App` action in a file that you created by yourself, you have to add `module.exports =` to the `App` action:

```js
module.exports = async function App() {

};
```

**Comment by dcsan** [comment]
OK. actually I shifted to using [botkit](https://github.com/howdyai/botkit)

I was wondering if this project has anything equivalent to botkit conversations?

**Comment by chentsulin** [comment]
@dcsan We have experimented slot filling mechanism internally in our company for several months. 

We are planning to roll it out in April or May. I will let you know when it's ready.

**Comment by chentsulin** [comment]
Hi @dcsan,
our internal conversation proposal repository is public now.
https://github.com/Yoctol/bottender-proposal-conversation

We have done a lot of experiments, so it should works in most cases.
