### ISSUE TITLE
Runnning example gets `error occurred in provider dev: spawn UNKNOWN`

### ISSUE THREAD

**Issue by ykchong45** [Yoctol/bottender#998]
I tried running `npm install` and `npm run dev` in `examples/slack-hello-world`, but I got this error message:

```
> dev
> bottender dev

× An unexpected error occurred in provider dev: spawn UNKNOWN
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at startProcess (C:\yk\0-test\bottender-master\bottender-master\examples\slack-hello-world\node_modules\ngrok\process.js:39:16)
    at getProcess (C:\yk\0-test\bottender-master\bottender-master\examples\slack-hello-world\node_modules\ngrok\process.js:23:20)
    at Object.connect (C:\yk\0-test\bottender-master\bottender-master\examples\slack-hello-world\node_modules\ngrok\index.js:16:22)
    at C:\yk\0-test\bottender-master\bottender-master\examples\slack-hello-world\node_modules\bottender\dist\cli\providers\sh\dev.js:62:41
    at Generator.next (<anonymous>)
    at C:\yk\0-test\bottender-master\bottender-master\examples\slack-hello-world\node_modules\bottender\dist\cli\providers\sh\dev.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\yk\0-test\bottender-master\bottender-master\examples\slack-hello-world\node_modules\bottender\dist\cli\providers\sh\dev.js:4:12)
App has started
server is running on 5000 port...
```

### What I Tried

Disabled "Firewall & network protection" under Windows Security.

**Comment by TaQuangKhoi** [comment]
Hi @ykchong45, Did you fix this issue?

**Comment by Leon840113** [comment]
me too, the sama error
